<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>True</UseWindowsForms>
    <UseWPF>True</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Z8ZusiBfpl\Z8ZusiBfpl.csproj" />
  </ItemGroup>

</Project>
